#!/usr/bin/env bash

set -e

[ -n "$BOOTSTRAPPER_DEBUG" ] && set -x

resolve_link() {
	$(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
	local cwd="$(pwd)"
	local path="$1"

	while [ -n "$path" ]; do
		cd "${path%/*}"
		local name="${path##*/}"
		path="$(resolve_link "$name" || true)"
	done

	pwd
	cd "$cwd"
}

shopt -s nullglob

bin_path="$(abs_dirname "$0")"
export PATH="${bin_path}:${PATH}"

shopt -u nullglob

command="$1"
case $command in
"" | "-h" | "--help")
	echo "bootstrapper 0.0.0" >&2
	echo "Welcome to the Concur Platform R&D bootstrapper!"
	echo "Be prepared to turn your laptop (or desktop, no haters here)"
	echo "into an awesome development machine."
	echo "$(bootstrapper-help)" >&2
	;;
*)
	command_path="$(command -v "bootstrapper-$command" || true)"
	if [ -z "$command_path" ]; then
		echo "bootstrapper: no such command \`$command'" >&2
		exit 1
	fi

	shift 1
	exec "$command_path" "$@"
	;;
esac
